name: CI Workflow

on:
  push:
    branches:
      - main
      - jenkin
  pull_request:
    branches:
      - main
      - jenkin

jobs:
  run-jenkinsfile:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Download Jenkinsfile Runner
      run: |
        wget https://repo.jenkins-ci.org/releases/io/jenkins/jenkinsfile-runner/jenkinsfile-runner/1.0-beta-29/jenkinsfile-runner-1.0-beta-29-app.zip
        unzip jenkinsfile-runner-1.0-beta-29-app.zip
        chmod +x jenkinsfile-runner/bin/jenkinsfile-runner
    
    - name: Run Jenkinsfile
      uses: jenkinsci/jenkinsfile-runner-github-actions/jenkinsfile-runner-prepackaged@v1
      with:
        jenkinsfile: './Jenkinsfile'